[codec]
order        = [ "H.264", "RFX" ]
h264_encoder = "OpenH264"

[OpenH264.default]
TargetBitrate    = 8000000
MaxBitrate       = 15000000
MaxFrameRate     = 60
EnableFrameSkip  = true

[OpenH264.lan]
TargetBitrate    = 8000000
MaxBitrate       = 15000000
MaxFrameRate     = 60
EnableFrameSkip  = false

[OpenH264.wan]
TargetBitrate    = 4000000
MaxBitrate       = 6000000
MaxFrameRate     = 30
EnableFrameSkip  = true

[OpenH264.broadband_high]
TargetBitrate    = 5000000
MaxBitrate       = 8000000
MaxFrameRate     = 30
EnableFrameSkip  = true

[OpenH264.satellite]
TargetBitrate    = 3000000
MaxBitrate       = 6000000
MaxFrameRate     = 24
EnableFrameSkip  = true

[OpenH264.broadband_low]
TargetBitrate    = 2000000
MaxBitrate       = 3000000
MaxFrameRate     = 20
EnableFrameSkip  = true

[OpenH264.modem]
TargetBitrate    = 120000
MaxBitrate       = 160000
MaxFrameRate     = 10
EnableFrameSkip  = true

