[codec]
order        = [ "H.264", "RFX" ]
h264_encoder = "OpenH264"

[OpenH264.default]
TargetBitrate    = 8000000
MaxBitrate       = 10000000
MaxFrameRate     = 30
EnableFrameSkip  = true

[OpenH264.lan]
TargetBitrate    = 12000000
MaxBitrate       = 18000000
MaxFrameRate     = 60
EnableFrameSkip  = false

[OpenH264.wan]
TargetBitrate    = 6000000
MaxBitrate       = 8000000
MaxFrameRate     = 30
EnableFrameSkip  = true

[OpenH264.broadband_high]
TargetBitrate    = 5000000
MaxBitrate       = 8000000
MaxFrameRate     = 30
EnableFrameSkip  = true

[OpenH264.broadband_low]
TargetBitrate    = 2000000
MaxBitrate       = 3000000
MaxFrameRate     = 24
EnableFrameSkip  = true

[OpenH264.satellite]
TargetBitrate    = 1500000
MaxBitrate       = 3000000
MaxFrameRate     = 20
EnableFrameSkip  = true

[OpenH264.modem]
TargetBitrate    = 256000
MaxBitrate       = 384000
MaxFrameRate     = 12
EnableFrameSkip  = true

