name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # alpine
          - dist: alpine
            version: "3.19"
          - dist: alpine
            version: "3.20"
          - dist: alpine
            version: "3.21"
          - dist: alpine
            version: "3.22"
          - dist: alpine
            version: "3.23"
          - dist: alpine
            version: "3.24"
          - dist: alpine
            version: "latest"
          - dist: alpine
            version: "edge"
          # debian
          - dist: debian
            version: "12-slim"
          - dist: debian
            version: "13-slim"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@2e76993ec4585e058ea832c23ee3d885970936af
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine the Docker tag
        id: get_tag
        run: |
          if [[ "${BASE}" == "alpine-latest" ]]; then
            echo "tag=latest ${BASE}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${BASE}" >> "$GITHUB_OUTPUT"
          fi
        env:
          BASE: ${{ matrix.dist }}-${{ matrix.version }}

      - name: Build Container image
        uses: redhat-actions/buildah-build@061ffd31bb5c3f8733a6f9bbdf00a9fb02eb708c
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ steps.get_tag.outputs.tag }}
          containerfiles: ./dockerfile
          build-args: |
            DIST=${{ matrix.dist }}
            VERSION=${{ matrix.version }}

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@3916dcf329473955be3059ef62c9c062ea1b9054
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ steps.get_tag.outputs.tag }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

